# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: tianjun
      MONGO_INITDB_ROOT_PASSWORD: 1qaz@WSX

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8088:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: tianjun
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1qaz@WSX
      ME_CONFIG_MONGODB_URL: mongodb://tianjun:1qaz@WSX@mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: 1qaz@WSX